export const circleWrapper = '[data-cy="circleWrapper"]'
export const circleChangingStyle = '[class*=circle_changing]'
export const circleModifiedStyle = '[class*=circle_modified]'
export const circleDefaultStyle = '[class*=circle_default]'
export const circleSelector = '[data-cy="circle"]'